# Generated by Django 5.0.2 on 2024-03-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=10)),
                ('city', models.CharField(default='Bhopal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('mathe', models.IntegerField(default=0)),
                ('biology', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
    ]
