# Generated by Django 5.0.2 on 2024-03-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
    ]
