# Generated by Django 5.0.2 on 2024-03-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_students_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=10)),
                ('city', models.CharField(default='Bhopal', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='marks',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_details'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
