# Generated by Django 5.0.2 on 2024-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_details_alter_marks_roll_no_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
